# Generated by Django 5.2.1 on 2025-05-29 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cultivos/')),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad_medida', models.CharField(default='kg', max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('REGISTRO', 'Registro'), ('COSECHA', 'Cosecha'), ('PUBLICADO', 'Publicado')], default='REGISTRO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cultivos', to='market_app.productodemercado')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
